### PR TITLE
Feature/transaction argument

### PR DESCRIPTION
**Pull request by gileCAD**

### CODE REVIEW

**Comment by kdub-nz** [comment]
>[Feature/transaction argument](https://github.com/gileCAD/Gile.AutoCAD.Extension/pull/11?notification_referrer_id=NT_kwDOACsvV7I5NDcyMjQyNDU3OjI4MzAxNjc#top)
#11

Hi Gilles,
I really like this amendment.
Requiring the passing of a transaction is much more transparent,
and as the  db can be determined from the transaction may make using methods with side databases a little cleaner ( if I understand correctly ).

Regards,
Kerry

**Comment by gileCAD** [comment]
Thanks Kerry.
The main motivation was to be able to call these methods from an OpenCloseTransaction (or from a nested transaction).
[This advice](https://forums.autodesk.com/t5/net/can-i-start-transactions-inside-the-application-idle-event/m-p/12527077/highlight/true#M80315) from Tony Tanzillo definitely made me decide to do it.

**Comment by stenci** [comment]
Hi Gilles,
I made a similar refactoring, but in my version I made the transaction optional. If the transaction is provided, then it is used, if it is not provided, then the old behavior remains. 

If I understand, your change instead is a breaking change because the transaction is always required.

I agree with the advice in that post, that's why I added the transaction argument (as mentioned [here](https://forums.autodesk.com/t5/net/can-i-start-transactions-inside-the-application-idle-event/m-p/12537247/highlight/true#M80410)), but I thought I would make it optional so (1) it's not a breaking change and (2) the simple behavior in simple cases is preserved. Ain't broke, don't fix it.

This is an example of my implementation, where I added an optional argument at the end of the list, then I pass it to the next call that requires it:
```C#
public static Dictionary<string, AttributeReference> AddAttributeReferences(this BlockReference target, Dictionary<string, string> attribValues, Transaction trans = null)
{
    Assert.IsNotNull(target, nameof(target));

    Transaction tr = trans ?? target.Database.GetTopTransaction();

    BlockTableRecord btr = target.BlockTableRecord.GetObject<BlockTableRecord>(trans: tr);
```

By adding the optional argument at the end of the list, the change is not breaking. The only exception is when there is a `params` argument, as in this case:
```C#
public static void SetXDictionaryXrecordData(this DBObject target, string key, Transaction trans = null, params TypedValue[] values)
```

There are three such instances (methods that have `params` and need a transaction) and perhaps I should have created a new overload rather than adding the optional argument. I am more familiar with Python than C#, and I did it the Python way.

I would like to know your opinion about adding the transaction as optional and keeping the change non-breaking vs making the transaction argument required.

**Comment by gileCAD** [comment]
stenci,
My first thought was to do exactly what you did. But in the end, I preferred to use a non-optional argument to avoid any confusion.

**Comment by gileCAD** [comment]
stenci,
Another thing that motivated my final choice is how we would call a method with multiple default arguments, like `GetObjects<T>`, when we want to specify a transaction (last argument).
```db.GetModelSpace(OpenMode.ForRead, tr).GetObjects<BlockReference>(OpenMode.ForRead, false, false, tr);```
or
```db.GetModelSpace(trans: tr).GetObjects<BlockReference>(trans: tr);```

**Comment by stenci** [comment]
Hi Gilles,

To me, coming from Python, using the form `db.GetModelSpace(trans: tr).GetObjects<BlockReference>(trans: tr);` comes natural. I use and abuse optional parameters in Python (and in more complex cases I use the [keyword only argument](https://docs.python.org/3/tutorial/controlflow.html#keyword-only-arguments) `*` operator to indicate that some arguments must be assigned by name.)

In C# there is no equivalent of Python's `*` operator, perhaps that's a message that I shouldn't use and abuse optional parameters.

And that's why I came here and asked: I don't want to use C# as if it were Python (I would love to, but I can't), I want to use it the way it's supposed to be used. I want to learn best practices and patterns from people that know C#, not from my knowledge of Python.

**Comment by kdub-nz** [comment]
My thought is that making passing a transaction mandatory is correct.
The (breaking) changes will be picked up by the compiler nicely, so there
will be no runtime ramifications.

Transparency and consistency is important  to remove surprises.
Correctness aside, because I'm having a separate code base for ac2025 the
change will be easier to manage for me.

Regards,

**Pull request merged**
